export interface IOrganisation {
    short_code_org: string,
    code: string,
    address_1: string,
    address_2: string,
    address_3: string,
    code_postal: string,
    ville: string,
    country: string,
    code_pays: string,
    tva: string,
    url_site_web: string,
    tel_admin: number,
    email_compta: string,
    type_organisation: string,
    total_employe: number,
    langue: string,
    type_organigramme: string,
    date_DEBUT: Date,
    date_FIN: Date,
    role: string,
    logo: string,
    id_menu: string,
    id_color_type: string,
    nbre_niveau_hierarchique: number
};